### ISSUE TITLE
0.5.0 no longer works with Django < 1.6

### ISSUE THREAD

**Issue by enoren** [niwinz/djorm-ext-pgbytea#4]
There is an issue on line 66 of bytea.py in the to_python method that it expects six.memoryview to be available, however that was not added in django.utils.six until 1.6 and is also not an attribute on the base six library at all, so if there is an ImportError this will fail as well.

To patch my local code I just put this snippet(pulled from the django 1.6 version of six) within some code that would be executed prior to leveraging the ByteaField:

```
from django.utils import six

if six.PY3:
    six.memoryview = memoryview
else:
    # memoryview and buffer are not stricly equivalent, but should be fine for
    # django core usage (mainly BinaryField). However, Jython doesn't support
    # buffer (see http://bugs.jython.org/issue1521), so we have to be careful.
    if sys.platform.startswith('java'):
        six.memoryview = memoryview
    else:
        six.memoryview = buffer
```

**Comment by niwinz** [comment]
Sorry for my late response! Thanks for report it.

I will fix it in this weekend ;)

**Comment by withtypes** [comment]
Hi! Did you find time to fix this?

**Comment by niwinz** [comment]
Sorry.

I forget comment about it! Yes, it should be fixed. I have included purposed code in compat module: https://github.com/niwibe/djorm-ext-pgbytea/commit/cf11138b634ddc5d4c7adabea1df1848dcef3aa8

**Comment by withtypes** [comment]
OK, thanks! I haven't noticed because 0.6.0 is not on PyPI https://pypi.python.org/pypi/djorm-ext-pgbytea I'll try it now.
